# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift (Xcode Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      # Optional: Explicitly select an Xcode version if needed
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build App
      run: |
        xcodebuild -project DoubleClips.xcodeproj \
                   -scheme DoubleClips \
                   -destination 'platform=iOS Simulator, arch=arm64, id=11BD9C44-D8FB-451C-8DB8-21EBADEABB63, OS=18.5, name=iPhone 17 Pro' \
                   build
